version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx.Dockerfile
    ports:
      - '8888:80'
    volumes:
      - './:/var/www/books'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
    links:
      - php

  php:
    container_name: test-books-app
    build:
      context: .
      dockerfile: ./docker/php.Dockerfile
    volumes:
      - './:/var/www/books'
    links:
        - mysql
  mysql:
    build:
      context: .
      dockerfile: ./docker/mysql.Dockerfile
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=books_db
